export const FETCH_ARTICLE_REQUEST = "FETCH_ARTICLE_REQUEST";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_FAILURE = "FETCH_ARTICLE_FAILURE";

export const FETCH_SEARCHBAR_REQUEST = "FETCH_SEARCHBAR_REQUEST";
export const FETCH_SEARCHBAR_SUCCESS = "FETCH_SEARCHBAR_SUCCESS";
export const FETCH_SEARCHBAR_FAILURE = "FETCH_SEARCHBAR_FAILURE";
